### ISSUE TITLE
text-align: center will misalign  color picker

### ISSUE THREAD

**Issue by peerbolte** [stijlbreuk/vue-color-picker-wheel#5]
When using `text-align: center` it will mess up the color-picker. You can try by adding `text-align: center` to the style in `/examples/App.vue`.

<img width="1501" alt="screen shot 2018-11-08 at 07 36 56" src="https://user-images.githubusercontent.com/6849898/48181861-69068780-e329-11e8-92a6-93ba16ff5b59.png">

**Comment by nino-vrijman** [comment]
Fixed in https://github.com/stijlbreuk/vue-color-picker-wheel/pull/8 and available in version 0.4.0 on npm.
