### ISSUE TITLE
Color selection failing when browser window is scrolled

### ISSUE THREAD

**Issue by gpandrew** [stijlbreuk/vue-color-picker-wheel#9]
I found that the color picker was not following my mouse clicks correctly.  I tracked the problem down to widgetCoords(event), which was returning incorrect co-ordinates when the browser window was scrolled away from the start position.
Suggested solution: replace all instances of pageX and pageY with clientX and clientY.

**Comment by peerbolte** [comment]
@gpandrew Thank you very much for reporting the bug! We will look into it and fix it asap.

**Comment by nino-vrijman** [comment]
Fixed in version 0.4.2, which should be available on npm right now!
